routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// dd(App::environment());

Auth::routes();

Route::get('/test', function(){
    // return config('database.connections.mysql.database');
});

Route::get('/switch-account', function(){
    // 6 nabeel
    // 2 faheem
    // auth()->loginUsingId(6);
    return redirect('/');
    // return config('database.connections.mysql.database');
});

Route::group(['middleware'=> 'auth'], function (){

    Route::name('choose.company')->get('/choose-company', 'HomeController@choose_company');

    Route::name('choose.company')->post('/choose-company', 'HomeController@choose_company');
});

Route::group(['middleware'=> ['auth', 'check_company']], function ()
{
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/', 'HomeController@index');

    Route::group(['prefix'=> 'users'], function(){

        Route::name('users')->get('/', 'UserController@index');

        Route::name('profile')->get('/profile/{from?}/{to?}', 'UserController@profile');

        Route::name('post.profile')->post('/profile', 'UserController@profile_store');

        Route::name('edit.users')->get('/{user}/edit', 'UserController@edit');

        Route::name('users.change.password')->get('/{user}/change-password', 'ChangePasswordController@form');

        Route::name('users.change.password.post')->post('/{user}/change-password', 'ChangePasswordController@store');

        Route::name('udpate.users')->put('/{user}', 'UserController@update');

        Route::name('delete.users')->get('/{user}/delete', 'UserController@distroy');

        Route::name('roles')->get('/roles', 'RolesController@index');

        Route::name('roles.create')->get('/roles/create', 'RolesController@create');

        Route::name('roles.store')->post('/roles', 'RolesController@store');

        Route::name('roles.edit')->get('/roles/{role}/edit', 'RolesController@edit');

        Route::name('roles.update')->put('/roles/{role}', 'RolesController@update');

        Route::name('roles.delete')->delete('/roles/{role}', 'RolesController@destroy');

        Route::group(['prefix'=> 'permissions'], function(){

            Route::name('permissions')->get('/', 'PermissionsController@index');

            Route::name('permissions.store')->post('/', 'PermissionsController@store');

            Route::name('permissions.create')->get('/create', 'PermissionsController@create');

            Route::name('permissions.edit')->get('/{permission}/edit', 'PermissionsController@edit');

            Route::name('permissions.update')->put('/{permission}', 'PermissionsController@update');

            Route::name('permissions.delete')->get('/{permission}/delete', 'PermissionsController@destroy');

        });

    });

    Route::group(['prefix'=> 'tasks'], function(){

        Route::name('tasks')->get('/', 'TasksController@index');

        // Route::name('tasks.rfs')->get('/rfs', 'TasksController@rfs');

        Route::name('tasks.create')->get('/create', 'TasksController@create');

        Route::name('tasks.store')->post('/', 'TasksController@store');

        Route::name('tasks.show')->get('/{task}/show', 'TasksController@show');

        Route::name('tasks.revise')->get('/{task}/revise', 'TasksController@revise');

        Route::name('tasks.revise.store')->post('/{task}/revise', 'TasksController@reviseStore');

        Route::name('tasks.changeOrderType')->get('/{task}/change-order-type', 'TasksController@changeOrderType');

        Route::name('tasks.changeOrderType.store')->post('/{task}/change-order-type', 'TasksController@changeOrderTypeStore');

        Route::name('tasks.addMoreFiles')->get('/{task}/add-files', 'TasksController@addMoreFilesForm');

        Route::name('tasks.file.delete')->delete('/{task}/{file}/delete', 'TasksController@deleteSubmittedFile');

        Route::name('tasks.review')->get('/{task}/review', 'TasksController@review');

        Route::name('tasks.review.store')->post('/{task}/review', 'TasksController@reviewStore');

        Route::name('tasks.assign')->get('/{task}/assign', 'TasksController@assign');

        Route::name('tasks.store.assign')->post('/{task}/assign', 'TasksController@storeAssign');

        Route::name('tasks.edit')->get('/{task}/edit', 'TasksController@edit');

        Route::name('tasks.delete')->get('/{task}/delete', 'TasksController@destroy');

        Route::name('tasks.submit')->get('/{task}/{submit?}', 'TasksController@edit');

        Route::name('tasks.update')->put('/{task}/{submit?}', 'TasksController@update');

    });

    Route::group(['prefix'=> 'clients'], function(){

        Route::name('clients')->get('/', 'ClientsController@index');

        Route::name('clients.create')->get('/create', 'ClientsController@create');

        Route::name('clients.store')->post('/', 'ClientsController@store');

        Route::name('clients.show')->get('/{client}/show', 'ClientsController@show');

        Route::name('clients.edit')->get('/{client}/edit', 'ClientsController@edit');

        Route::name('clients.update')->put('/{client}', 'ClientsController@update');

        Route::name('clients.delete')->get('/{client}/delete', 'ClientsController@destroy');

    });

    Route::group(['prefix'=> 'reports', 'namespace' => 'Reports'], function(){

        Route::name('bonus-test')->get('/bonus-test', 'BonusController@temp_bonus');
        Route::name('bonus')->get('/bonus', 'BonusController@index');
        Route::name('bonus.pdf')->get('/pdf/bonus', 'BonusController@pdf');
        Route::name('reports.today_task')->get('/today-task', 'ReportController@today_tasks');
        Route::name('reports.orders.invoice.excel')->get('/orders-invoices/excel/{client}/{from_date?}/{end_date?}/{design_type?}', 'InvoiceController@excel');
        Route::name('reports.orders.invoice.pdf')->get('/orders-invoices/pdf/{client}/{from_date?}/{end_date?}/{design_type?}', 'InvoiceController@pdf');
        Route::name('reports.orders.invoice')->get('/orders-invoices/{start_date?}/{end_date?}/{design_type?}', 'InvoiceController@form');
        Route::name('reports.orders.sales')->get('/sales-bonus/{start_date?}/{end_date?}', 'SalesBonusController@index');
        Route::name('reports.orders.sales')->post('/sales-bonus/{start_date?}/{end_date?}', 'SalesBonusController@pdf');
        Route::name('reports.sales.customers.orders')->get('/sales-customers', 'SalesCustomersController@index');
        Route::name('reports.sales.customers.orders')->post('/sales-customers', 'SalesCustomersController@pdf');

    });

    Route::name('settings')->get('/settings', 'SettingsController@index');

    Route::name('settings.post')->post('/settings/{tab}', 'SettingsController@store');

    Route::group(['prefix'=> 'select'], function()
    {
        Route::name('select.country')->post('/countries', 'Api\Select2Controller@countries');

        Route::name('select.client')->post('/clients', 'Api\Select2Controller@clients');

        Route::name('select.user')->post('/users', 'Api\Select2Controller@users');
    });

    Route::get('/notifications', 'NotificationsController@index')->name('notifications');

});

Route::group(['prefix'=>'datatables'], function ()
{
    Route::name('dt.users')->get('/', 'Datatables\UserTableController@getData');

    Route::name('dt.roles')->get('/roles', 'Datatables\RolesTableController@index');

    Route::name('dt.clients')->get('/clients', 'Datatables\ClientTableController@getData');

    Route::name('dt.tasks')->get('/tasks', 'Datatables\TasksTableController@getData');

});

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/search', 'SearchController@index')->name('route.search');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::group(['prefix' => 'seeds-generator', 'namespace' => 'Generators', 'middleware' => ['web', 'auth']], function () {
    Route::get('roles-permissions','RoleandseedControllers@index');
});


Route::get('/clear', function(){
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');
    dd(Artisan::call('storage:link'));
});

Route::get('/my-link', function(){
    dd(Artisan::call('storage:link'));
});

Route::get('/make-controller', function(){
    dd(Artisan::call('make:controller', ['name' => 'Sales/Auth/MyAuthController']));
});

app/Models/Sales/Call.php
<?php

namespace App\Models\Sales;

use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    protected $fillable = [ 'subject', 'duration', 'feedback', 'details' ];

    public function lead()
    {
        return $this->belongsTo(Lead::class);
    }

    public function owner()
    {
        return $this->belongsTo(\App\User::class, 'created_by');
    }
}

app/Http/Controllers/Sales/ActivitiesController.php
<?php

namespace App\Http\Controllers\Sales;

use App\Models\Sales\Call;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivitiesController extends Controller
{
    public function index()
    {
        $calls = Call::with('owner')->get();
        return view('sales.activities.index', compact('calls'));
    }
}

app/Http/Controllers/Sales/CallsController.php
<?php

namespace App\Http\Controllers\Sales;

use App\Models\Sales\Call;
use App\Models\Sales\Lead;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CallsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $leads = Lead::doesntHave('calls')->get();
        return view('sales.calls.index', ['leads' => $leads]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Lead $lead
     * @return \Illuminate\Http\Response
     */
    public function create(Lead $lead)
    {
        return view('sales.calls.create', ['call' => new Call(), 'lead' => $lead]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Lead $lead
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function store(Request $request, Lead $lead)
    {
        $this->validateFields($request);
        $call = new Call($request->all());
        $call->lead()->associate($lead);
        auth()->user()->leads()->save($call);
        activity_log("Created new Lead ({$call->subject})", $call);
        return redirect()->route('leads.calls.index', ['lead' => $lead->id])->with('message', 'Call Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  Call $call
     * @return \Illuminate\Http\Response
     */
    public function show(Call $call)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Call $call)
    {
        return view('sales.calls.index', ['call' => $call]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Call $call)
    {
        $this->validateFields($request);
        $call->fill($request->all());
        $call->save();
    }

    protected function validateFields(Request $request)
    {
        $request->validate([
            'subject' => 'required',
            'lead_id' => 'required|exists:leads,id',
            'duration' => 'required',
            'feedback' => 'required',
            'details' => 'required',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Call $call
     * @return \Illuminate\Http\Response
     */
    public function destroy(Call $call)
    {
        //
    }
}

app/Http/Controllers/Sales/LeadsController.php
<?php

namespace App\Http\Controllers\Sales;

use App\Models\Client;
use App\Models\Company;
use App\Models\Sales\Lead;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class LeadsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $leads = auth()->user()->leads()->withCount('calls')->get();
        return view('sales.leads.index', ['leads' => $leads]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function callingList()
    {
        $leads = Lead::doesntHave('calls')->get();
        return view('sales.leads.index', ['leads' => $leads, 'isCallingList' => true]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('sales.leads.create', ['lead' => new Lead()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return Response
     * @throws \Exception
     */
    public function store(Request $request)
    {
        $this->validateFields($request);
        $lead = new Lead($request->all());
        auth()->user()->leads()->save($lead);
        $lead->save();
        activity_log("Created new Lead ({$lead->name})", $lead);
        return redirect()->route('leads.index')->with('message', 'Leads Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show(Lead $lead)
    {
        $lead->load('calls.owner');
        return view('sales.leads.show', compact('lead'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Lead $lead
     * @return Response
     */
    public function edit(Lead $lead)
    {
        return view('sales.leads.create', ['lead' => $lead]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Lead $lead
     * @return Response
     * @throws \Exception
     */
    public function update(Request $request, Lead $lead)
    {
        $this->validateFields($request);
        $lead->fill($request->all());
        $lead->save();
        activity_log("{$lead->name} Updated", $lead);
        return redirect()->route('leads.index')->with('message', 'Leads Updated Successfully');
    }

    protected function validateFields(Request $request)
    {
        $request->validate([
            'company' => 'required',
            'email' => 'required',
            'state' => 'required',
            'city' => 'required',
            'country_id' => 'required|exists:countries,id',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Lead $lead
     * @return Response
     * @throws \Exception
     */
    public function destroy(Lead $lead)
    {
        $lead->delete();
        activity_log("{$lead->name} Deleted!", $lead);
        return redirect()->route('leads.index')->with('message', 'Leads Deleted Successfully');
    }

    /**
     * Move Lead to Clients List and softDelete from Leads.
     *
     * @param  Lead $lead
     * @return Response
     * @throws \Exception
     */
    public function moveToCustomer(Lead $lead)
    {
        $client = new Client();
        $client->name = $lead->name;
        $client->nick_name = $lead->name;
        $client->company = $lead->company;
        $client->email = $lead->email;
        $client->country_id = $lead->country_id;
        $client->phone = $lead->phone;
        $client->address = $lead->address;
        $client->instructions = $lead->description;
        $client->secret_instructions = '';
        $client->company_id = Company::first()->id;
        $client->is_active = 1;
        $client->from_lead = 1;

        auth()->user()->clients()->save($client);

        $lead->delete();

        activity_log("{$lead->name} moved to clients!", $lead);
        return redirect()->route('leads.index')->with('message', 'Leads moved to clients successfully');
    }

    function select2()
    {
        $record = Lead::where('name', 'LIKE', '%' . request('q') . '%')
            ->select(['name AS name', 'id AS id'])->paginate(10);
        return $record;
    }
}

app/Http/Controllers/Sales/SalesController.php
<?php

namespace App\Http\Controllers\Sales;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SalesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:sales');
    }

    public function index()
    {
        return view('sales.dashboard');
    }
}

resources/views/sales/leads/create.blade.php
@extends('sales.layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @if($lead->id)
                        Update Lead
                    @else
                        Add new Leads
                    @endif
                </div>

                <div class="card-body">

                    <form method="POST" action="{{ $lead->id? route('leads.update', ['lead' => $lead->id]) :route('leads.store') }}">
                        @csrf
                        @if($lead->id)
                            @method('put')
                        @endif

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="company_name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                       name="name" value="{{ old('name', $lead->name) }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="company_name" class="col-md-4 col-form-label text-md-right">Company Name</label>
                            <div class="col-md-6">
                                <input id="company_name" type="text" class="form-control{{ $errors->has('company') ? ' is-invalid' : '' }}"
                                       name="company" value="{{ old('company', $lead->company) }}" required autofocus>
                                @if ($errors->has('company'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('company') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Phone</label>

                            <div class="col-md-6">
                                <input id="phone" type="tel" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone', $lead->phone) }}" required>

                                @if ($errors->has('phone'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mobile" class="col-md-4 col-form-label text-md-right">Mobile</label>

                            <div class="col-md-6">
                                <input id="mobile" type="tel" class="form-control{{ $errors->has('mobile') ? ' is-invalid' : '' }}" name="mobile" value="{{ old('mobile', $lead->mobile) }}">

                                @if ($errors->has('mobile'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('mobile') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email', $lead->email) }}">

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="city" class="col-md-4 col-form-label text-md-right">City</label>

                            <div class="col-md-6">
                                <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city', $lead->city) }}" required>

                                @if ($errors->has('city'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="state" class="col-md-4 col-form-label text-md-right">State</label>

                            <div class="col-md-6">
                                <input id="state" type="text" class="form-control{{ $errors->has('state') ? ' is-invalid' : '' }}" name="state" value="{{ old('state', $lead->state) }}">

                                @if ($errors->has('state'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('state') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="country_id" class="col-md-4 col-form-label text-md-right">Country</label>

                            <div class="col-md-6">
                                <select name="country_id" id="country_id" class="form-control{{ $errors->has('state') ? ' is-invalid' : '' }}">
                                    @foreach(App\Models\Country::all() as $country)
                                        <option value="{{ $country->id }}">{{ $country->name }}</option>
                                    @endforeach

                                </select>
                                @if ($errors->has('country_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('country_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>

                            <div class="col-md-6">
                                <textarea id="address" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address">{{ old('address', $lead->address) }}</textarea>

                                @if ($errors->has('address'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description">{{ old('description', $lead->description) }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{{ route('leads.index') }}" class="btn btn-primary">Cancel</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/sales/leads/index.blade.php
@extends('sales.layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if(!count($leads))
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title">My Calling List</h5>
                        <h5 class="card-subtitle mb-2 text-muted">No records found!</h5>
                    </div>
                </div>
            @else

            <div class="card">
                <div class="card-header">Leads</div>

                <div class="card-body">

                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Customer no.</th>
                                <th>Name</th>
                                <th>Company</th>
                                <th>Phone</th>
                                <th>Email</th>
                                @empty($isCallingList)
                                    <th>Last Call on</th>
                                    <th>Last Feedback</th>
                                    <th>Total Calls</th>
                                @endempty
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($leads as $lead)
                            <tr>
                                <td>{{ $lead->id }}</td>
                                <td>{{ $lead->name }}</td>
                                <td>{{ $lead->company }}</td>
                                <td>{{ $lead->phone }}</td>
                                <td>{{ $lead->email }}</td>
                                @empty($isCallingList)
                                    <td>{{ optional($lead->last_call_at)->format('d/m/Y h:i:s A') }}</td>
                                    <td>{{ $lead->last_feedback }}</td>
                                    <td>{{ $lead->calls_count }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fa fa-ellipsis-v"></i>
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                <a class="dropdown-item" href="{{ route('leads.edit', ['lead' => $lead->id]) }}">Edit</a>
                                                <form action="{{ route('leads.delete', ['lead' => $lead->id]) }}" method="post">
                                                    @method('delete')
                                                    @csrf
                                                    <button type="submit" class="dropdown-item">Delete</button>
                                                </form>
                                                <a class="dropdown-item" href="{{ route('leads.calls.create', ['lead' => $lead->id]) }}">Schedule Call</a>
                                                <form action="{{ route('leads.move.to.customer', ['lead' => $lead->id]) }}" method="post">
                                                    @csrf
                                                    <button type="submit" class="dropdown-item">Move to Customer</button>
                                                </form>
                                                <a href="{{ route('leads.show', ['lead' => $lead->id]) }}" class="dropdown-item">History</a>
                                            </div>
                                        </div>
                                    </td>
                                @endempty
                                @if(isset($isCallingList))
                                    <td>
                                        <a href="{{ route('leads.calls.create', ['lead' => $lead->id]) }}"
                                           class="fa fa-phone fa-2x"></a>
                                    </td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            @endif

        </div>
    </div>
</div>

<a href="{{ route('leads.create') }}" id="fab">+</a>

@endsection